#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t six"

$L "**********************************************" 
$L "*************** Android 9.0 Pie **************" 
$L "************* Welcome to SiX ROM *************" 
$L "**********************************************" 
$L `getprop ro.build.version.release` / sixrom-`getprop ro.six.version`";
